query getInfo($repository: String!) {
    viewer {
        repository(name: $repository) {
            name
            createdAt
            updatedAt
            description
            homepageUrl
            isArchived
            isDisabled
            isFork
            isLocked
            isMirror
            isPrivate
            isTemplate
            owner {
                login
            }
            primaryLanguage {
                name
            }
            licenseInfo {
                name
            }
        }
    }
}
