query getContent($owner: String!, $repository: String!, $expression: String!) {
  repository(owner: $owner, name: $repository) {
    object(expression: $expression) {
      ... on Blob {
        text
      }
    }
  }
}
