query getId($owner: String!, $repository: String!, $branch: String!, $until: GitTimestamp!, $filePath: String!) {
  repository(owner: $owner, name: $repository) {
    ref(qualifiedName: $branch) {
      target {
        ... on Commit {
          history(path: $filePath, until: $until, first: 2) {
            nodes {
              oid
            }
          }
        }
      }
    }
  }
}
