query getLastCommit($owner: String!, $repository: String!, $branch: String!) {
  repository(owner: $owner, name: $repository) {
    object(expression: $branch) {
      ... on Commit {
        history(first: 1) {
          edges {
            node {
              commitUrl
              committer {
                name
              }
              committedDate
            }
          }
        }
      }
    }
  }
}
