name: Publish package

on:
    push:
        branches:
            - master
        tags:
            - v*

jobs:
    publish:
        name: Publish package
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master

            - name: Node.js setup
              uses: actions/setup-node@master
              with:
                  version: 10

            - name: Yarn build
              run: |
                  npm install -g yarn
                  yarn install
                  yarn build
            - name: Publish to registry
              uses: actions/npm@master
              env:
                  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
              with:
                  args: 'publish --access public'

    notify:
        name: Discord notification
        needs: publish

        steps:
            - name: Discord notification
              uses: Ilshidur/action-discord@master
              env:
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
              with:
                  args: 'gh-gql package has been publish on npm.'
